export const HOST = ''
export const MOUNTPOINT = '/slider'
export const OPEN = 255
export const CLOSED = 0
export const AXES = ['x', 'y', 'z']
export const MS_IN_MINUTE = 60000
export const STOP = 0
export const STEP = 1
export const STARTED = 2
export const MOVE = 3
export const STEPPED = 4